workflows:
    ionic-capacitor-android-workflow:
        name: Ionic Capacitor Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
            node: latest
        triggering:
            events:
                - push
                - pull_request
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
        scripts:
            - name: Install npm dependencies, Generate Resources and add Android from Capacitor
              script: |
                npm install
                npm run build
                npx cap add android
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
                npx cap copy
                npm run resources               
            - name: Build Android release
              script: |
                cd android
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
